wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719134999
    t:
      1:
      - 1
      - 41
      - 55
      - 100
      2:
      - 1
      - 41
      - 55
      - 100
      3:
      - 23
      4: 3.8.19
      5: 0.17.2
      8:
      - 3
      - 5
      13: windows-amd64
epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 1.0e-05
val_percent:
  desc: null
  value: 0.1
save_checkpoint:
  desc: null
  value: true
img_scale:
  desc: null
  value: 0.5
amp:
  desc: null
  value: false
