wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719134843
    t:
      1:
      - 1
      - 41
      - 55
      - 100
      3:
      - 23
      4: 3.8.19
      5: 0.17.2
      8:
      - 3
      - 5
      13: windows-amd64
